### ISSUE TITLE
relative rotation set by spécific angle Vector 3 in °

### ISSUE THREAD

**Issue by ShinoHarvest** [ficsit-felix/ficsit-felix#105]
hard make exact 90° or 180° (less hard just need invert number) to more exact to not lost snapping ability in game need make 89.91° angle, grant ability of this build
(vertical catwalk) https://cdn.discordapp.com/attachments/553550313533997057/666421208069439548/Screenshot20200114-00165700000.png

(more angle ramp)
https://imgur.com/DI40CCb

**Comment by bitowl** [comment]
In [version 0.0.18](https://github.com/ficsit-felix/ficsit-felix/releases/tag/v0.0.18) you can activate `Snapping` to snap angles to fixed increments (configurable in the settings).
You can also activate experimental property editing in `Settings` -> `Develop` -> `Show Properties Panel`. Then you can directly enter the euler angles for the objects.
![image](https://user-images.githubusercontent.com/1002285/84080208-1c3ed300-a9dc-11ea-8770-354e250a0337.png)
Does this solve your use case?
