### ISSUE TITLE
[Enhancement] Viewport anti-aliasing

### ISSUE THREAD

**Issue by CVex2150J** [ficsit-felix/ficsit-felix#3]
It is possible to increase the visual beauty of the ThreeJS Renderer by adding the antialias options when creating the WebGLRenderer. This is the browser built-in canvas antialias

https://github.com/bitowl/ficsit-felix/blob/d8cb8d32e9cc85494cc1759a0f7d18fbc57fe7dd/app/src/components/scene/Renderer.js#L14

`this.renderer = new WebGLRenderer({antialias:true});`

**Comment by bitowl** [comment]
Great suggestion! Thank you.
