### ISSUE TITLE
No longer works in Chrome for me as of 10/21/20

### ISSUE THREAD

**Issue by phatal808** [ficsit-felix/ficsit-felix#301]
I was using the application for awhile yesterday in Chrome.  I then went back to it and loaded up my same file and it does it's normal loading procedures except there is no map or objects shown just a blank screen where the map should be.  I tried the same file in Firefox and have no problems.
![ficsitfelixerror](https://user-images.githubusercontent.com/36393102/96953042-33c7b580-14be-11eb-91f0-68d031b964f2.png)

**Comment by bitowl** [comment]
I'm not able to reproduce this yet.
Does this always occur now? If yes, which version of chrome are you using (see chrome://settings/help)?
And are any errors showing in the console (Ctrl+Shift+J on windows)?

**Comment by phatal808** [comment]
It's a highly one off type issue I think.  I've used your tools for over a year and never had a problem unless coffee stain related.  Just all the sudden it started doing this.
There was an error caught.  I exported the error to a file, attached here.  I also recorded from start to finish my procedure and how your web app responds.  I chose to use a different file this time that was slightly older and smaller.  My current play through is 5 times the size of the file I loaded in the small video clip attached in the zip.  I mention this because with the larger savefile when loading, it pauses for a long time at 50% then continues with the same blank result.

Edit:  I went back and loaded my current save to check for errors as well and included the log export.  There is an additional error in it but seemingly not as severe.  It appears to have no bearing on your site, but I wanted to ask how I can fix the:
```
instrument.js:109 source connection of power line  not found.
(anonymous) @ instrument.js:109
```

Google Chrome is up to date
Version 86.0.4240.111 (Official Build) (64-bit)

[ficsit-felix.netlify.app-1603462382134.log](https://github.com/ficsit-felix/ficsit-felix/files/5429963/ficsit-felix.netlify.app-1603462382134.log)

[ficsit-felix.netlify.app-CurrentPlaythrough.log](https://github.com/ficsit-felix/ficsit-felix/files/5430042/ficsit-felix.netlify.app-CurrentPlaythrough.log)

[ficsitFelixError.zip](https://github.com/ficsit-felix/ficsit-felix/files/5429976/ficsitFelixError.zip)

Mods in CURRENT playthrough.  Less mods in the smaller savefile.
![image](https://user-images.githubusercontent.com/36393102/97016868-42908580-151b-11eb-841e-23a60fb5d037.png)

**Comment by bitowl** [comment]
Seems like something went wrong with the layout library.
It would be helpful if you can send the contents of the local storage (dev tools -> Application -> Local Storage, then double click on the Value and copy it)
![image](https://user-images.githubusercontent.com/1002285/97018726-c7959200-154f-11eb-96e8-7a5df2d4470b.png)

A workaround for this issue could be to open the settings from the open save file screen, expand the "Develop" options and reset all settings.
![image](https://user-images.githubusercontent.com/1002285/97019105-31ae3700-1550-11eb-8802-7289d9ed3c11.png)

The power line error is just a warning and is the result of a power line that has an empty string as `entity.extra.sourcePathName` and therefore cannot be rendered (as the connecting point cannot be determined).
I'm going to change the warning message to include the `pathName` of the power line so you can find the offending power line and check whether it should be connected to something or you can delete it.

**Comment by phatal808** [comment]
{"nearPlane":100,"farPlane":200000,"showModels":true,"showCustomPaints":true,"mapType":1,"conveyorBeltResolution":4,"editClassColors":false,"classColors":{},"locale":"en","experimentalFeatures":true,"autoLoadSaveFile":"","showFps":false,"showDevelopSettings":true,"layout":{"0":{"1":"0","2":"0","3":"1","t":"0","p":"0","blockedPopoutsThrowError":"0","closePopoutsOnUnload":"0","showPopoutIcon":"1","showMaximiseIcon":"0","showCloseIcon":"1","responsiveMode":"onload","tabOverlapAllowance":0,"reorderOnTabMenuClick":"0","tabControlOffset":10},"4":{"5":5,"6":10,"7":10,"8":22,"9":300,"u":15,"a":0},"b":{"c":"6","d":"7","e":"8","f":"9","popin":"pop in","tabDropdown":"additional tabs"},"g":[{"n":"0","l":"2","t":"0","vue":"___0","i":{},"o":"","g":[{"l":"4","k":48.61507128309572,"n":"0","t":"0","o":"","s":0,"g":[{"k":60,"l":"5","n":"1","t":"1","o":"Scene","vue":"0.0","i":{},"h":"Generic.Vue"}]},{"k":28.384928716904273,"n":"0","l":"3","t":"0","vue":"0.1","i":{},"o":"","g":[{"l":"4","m":47.172859450726975,"n":"0","t":"0","o":"","s":0,"g":[{"m":70,"l":"5","n":"1","t":"0","o":"Object List","vue":"0.1.0","i":{},"h":"Generic.Vue"}]},{"l":"4","m":52.827140549273025,"n":"0","t":"0","o":"","s":0,"g":[{"m":30,"l":"5","n":"1","t":"0","o":"Class List","vue":"0.1.1","i":{},"h":"Generic.Vue"}]}]},{"k":23,"s":0,"n":"0","l":"4","t":"0","vue":"0.2","i":{},"o":"","g":[{"l":"5","n":"1","t":"0","o":"JSON","vue":"0.2.0","i":{},"h":"Generic.Vue"},{"l":"5","n":"1","t":"0","o":"Properties","vue":"0.2.1","i":{},"h":"Generic.Vue"}]}]}],"n":"0","t":"0","o":"","q":[],"maximisedItemId":{}},"layoutVersion":1,"snapping":false,"translationSnap":100,"rotationSnap":45,"cameraType":1,"showPropertiesPanel":false}

**Comment by bitowl** [comment]
Thanks! With those layout settings I'm able to reproduce the error an can investigate this further.
