### ISSUE TITLE
Application launches as a blank black window since updating

### ISSUE THREAD

**Issue by BlogmasterAvery** [ficsit-felix/ficsit-felix#372]
Openned the app (unknown previous version) to look at my save, got some error about an enumerator and right after I clicked send report the popup for the new .30 update came up, so I clicked that and closed the app, waited a bit and re-openned it. Now it only appears as a blank black window, not even an X close button. Already tried reinstalling and restarting my computer but nothing changed.

**Comment by bitowl** [comment]
Thank you for reporting this bug!
It should be fixed in version [`0.0.31`](https://github.com/ficsit-felix/ficsit-felix/releases/tag/v0.0.31).
