### ISSUE TITLE
Create an electron app?

### ISSUE THREAD

**Issue by bitowl** [ficsit-felix/ficsit-felix#60]
or whatever is good these days for creating a windows application

might take the fear away from user who don't want their data in the browser (=internet for some)
could opem file browser directly in save folder
maybe add an option to watch a save file and automatically reload it if it changed

- [x] Create menu
- [x] Update menu when switching to editor page
- [x] Change menu when language is changed
- [x] Add go back to main screen button to menu
- [x] List files in SaveFiles folder
- [x] Save file to there
- [x] Make a backup of the previous file before
- [x] Hide menubar component in desktop version
- [x] Show progress bars as undismissable modal dialogs?
- [x] Set menu language correctly on the first load
- [x] Implement open file / import json menu entries
- [x] Specify save directory when exporting json
- [x] Make saving use progress bar dialog
- [x] Add ability to save file under different name (Different menu entry "Save as..."?)
- [x] Add confirmation dialogs before opening / saving
- [x] Show BugReportDialog when errors while opening
- [x] Parse save game headers to show additional information about the save
- [x] Group the saves by session the way it's done in Satisfactory
- [x] Figure out auto update
- [x] Correctly display sessionSaveDate
- [x] Sort saves by sessionSaveData
- [x] Sort sessions by sessionSaveDate
- [x] Make menu shortcuts work
- [x] Add reload and open debug menu in development
- [x] Open sidebar in editor by pressing ESC?
- [x] Confirm before exit
- [x] Put download button on web app
- [x] Fix saving on windows build (enable develop console?)
- [x] Fix download save name in web version
- [x] Fix commit hash and reading own LICENSE in Travis
- [x] Does Satisfactory support save files in subdirectories? If yes, read files from those folders as well and make sure to save back to the correct folder
- [x] Add save entry to side menubar as well
- [x] Rename saveConfirm on desktop
- [x] Also display save file size?
- [ ] Add an option to change save folder location
- [ ] Add option to use system titlebar
- [ ] Also mount the menu into the system titlebar
- [ ] Use desktopUtils.openFileAndMoveToEditor for web as well?

**Comment by bitowl-stream** [comment]
test

**Comment by bitowl** [comment]
test
